# This Docker Compose file is meant to be used on a development 
# environment for testing.
# This environment includes a fake local network, a local database and
# a volume mounted with the code to see changes on the go.
version: "3.8"

services:

  # RIoTPot is the container for the central node
  riotpot:
    build:
      context: ..
      dockerfile: ./build/docker/Dockerfile
    image: riotpot:development
    #command: 
    restart: always
    ports:
      # Ports under 60 might see errors when unquoted
      # https://stackoverflow.com/questions/58810789/quotes-on-docker-compose-yml-ports-make-any-difference
      - "7:7"
      # - "22:22"
      - "23:23"
      - "502:502"
      # - "8080:8080"
      - "1883:1883"
      - "5683:5683"
    env_file:
    - ../build/env/.env
    networks:
      - honeypot

networks:
  honeypot:
    name: honeypot
    driver: bridge
